// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0s4MUY49u6Irk_MIy5kNiJn7C9tB9u8',
    appId: '1:905690845790:web:bd385f16606d4b23311acf',
    messagingSenderId: '905690845790',
    projectId: 'gps-app-91bca',
    authDomain: 'gps-app-91bca.firebaseapp.com',
    databaseURL: 'https://gps-app-91bca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-app-91bca.firebasestorage.app',
    measurementId: 'G-0220BJSLGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdhSpBAsNhM1VC1O0ziJN5dzS6sE46oqI',
    appId: '1:905690845790:android:d0f8b4d750417cf1311acf',
    messagingSenderId: '905690845790',
    projectId: 'gps-app-91bca',
    databaseURL: 'https://gps-app-91bca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-app-91bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkb4GfHD2Y9XTSPLT3PV6k5qt7-UqeWbw',
    appId: '1:905690845790:ios:8a7daf332690b009311acf',
    messagingSenderId: '905690845790',
    projectId: 'gps-app-91bca',
    databaseURL: 'https://gps-app-91bca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-app-91bca.firebasestorage.app',
    iosClientId: '905690845790-0gt3n82dtl5jsvai6ao2q3h4jq1r47bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkb4GfHD2Y9XTSPLT3PV6k5qt7-UqeWbw',
    appId: '1:905690845790:ios:8a7daf332690b009311acf',
    messagingSenderId: '905690845790',
    projectId: 'gps-app-91bca',
    databaseURL: 'https://gps-app-91bca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-app-91bca.firebasestorage.app',
    iosClientId: '905690845790-0gt3n82dtl5jsvai6ao2q3h4jq1r47bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gpsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn0s4MUY49u6Irk_MIy5kNiJn7C9tB9u8',
    appId: '1:905690845790:web:a8d2838c020ec412311acf',
    messagingSenderId: '905690845790',
    projectId: 'gps-app-91bca',
    authDomain: 'gps-app-91bca.firebaseapp.com',
    databaseURL: 'https://gps-app-91bca-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gps-app-91bca.firebasestorage.app',
    measurementId: 'G-PM4MK6PR2Q',
  );
}
